name: Playwright Tests

on:
  push:
    branches: ["main", "develop"] # o la rama donde quieras ejecutar
  pull_request:
    branches: ["main", "develop"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      # Reemplaza la siguiente URL con la de tu aplicación desplegada
      BASE_URL: ${{ secrets.BASE_URL }}
      EUTAXIA_EMAIL: ${{ secrets.EUTAXIA_EMAIL }}
      EUTAXIA_PASSWORD: ${{ secrets.EUTAXIA_PASSWORD }}
      SECOND_EUTAXIA_EMAIL: ${{ secrets.SECOND_EUTAXIA_EMAIL }}
      SECOND_EUTAXIA_PASSWORD: ${{ secrets.SECOND_EUTAXIA_PASSWORD }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      CI: 2

    steps:
      - name: Checkout código
        uses: actions/checkout@v5

      - name: Instalar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar navegadores de Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar tests
        run: npx playwright test

      - name: Guardar reportes como artefacto
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 20

      # AÑADIDO: Subir el reporte para GitHub Pages
      - name: Subir informe para GitHub Pages
        if: always()
        uses: actions/upload-pages-artifact@v1
        with:
          path: playwright-report

      # AÑADIDO: Desplegar el reporte en GitHub Pages
      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v1
